### ISSUE TITLE
[Suggestion] - Out-of-battle Catching

### ISSUE THREAD

**Issue by FLalejandro** [Ordalca/Nuzlocke#2]
If any of the out-of-battle settings are set to true, PokeBalls should instantly break upon making contact with a Pokemon matching the spec, rather than the ball being wasted and a message saying "Catching Attempt blocked by Nuzlocke Rules".

**Comment by Ordalca** [comment]
It's actually breaking as soon as I can manage it, unless I tried blocking it as a projectile.  Do you mean "break" as in failed catch, or break as in breaking into multiple pieces you can craft back together?

**Comment by FLalejandro** [comment]
My bad, I should've been more specific.
By breaking, I meant it would either drop as itself or drop into pieces.
Blocking it as a projectile would also accomplish the same goal and I believe would be a better way to approach it.

Currently when I throw a ball, it begins the catching animation, but the catch always fails. Though, since it goes through the catching animation, the ball is lost completely.

**Comment by Ordalca** [comment]
Ok, I think I can do that.  I'll have that in the next version.

**Comment by Ordalca** [comment]
Added using commit 4d863b4.  Will be in v2.1
