### ISSUE TITLE
[Suggestion] - Add a "God-mode" option for Nuzlocke Runs

### ISSUE THREAD

**Issue by FLalejandro** [Ordalca/Nuzlocke#3]
For players running the 
`wipe-result: DEATH` 
setting for Hardcore playthroughs, it isn't ideal for a standard Vanilla death such as fall damage or drowning to be the end of a Nuzlocke. 

It'd be nice to see a feature such as:
`enable-passive-damage: true/false`
so that players can still continue to customize their playthrough, and decide whether or not they want to worry about vanilla factors potentially ending their run.

**Comment by FLalejandro** [comment]
Being able to toggle hunger would also be great for players who use Hardcore mode and can't disable Hunger unless they use a data pack!

**Comment by Ordalca** [comment]
Sure, easy enough, I think.  I think I'd leave hunger, and just remove the damage from starvation, though.  The berries can be eaten for short effects, but last I checked, many cannot be eaten unless you're hungry.

**Comment by Ordalca** [comment]
Added 3b5ff4fb implementing god-mode.  Is in v2.1
