### ISSUE TITLE
[Bug] - `/nuzlocke begin` can't be used in Hardcore mode

### ISSUE THREAD

**Issue by FLalejandro** [Ordalca/Nuzlocke#4]
Due to Hardcore automatically turning cheats off, players can not use the command 
`/nuzlocke begin` or another other nuzlocke command without opening to LAN and enabling cheats.

**Comment by Ordalca** [comment]
At what point should a Hardcore nuzlocke start, then?  Should it be immediately, or some other trigger?  I'll need to look up how to detect if cheats are enabled on 1.16.5, as well.  Difficulty only reports up to Hard.

**Comment by Ordalca** [comment]
Perhaps something like nuzlocke begins at first use of a healer or ball?  You spawn in a village, so it'd be easy enough to get to a healer.

**Comment by FLalejandro** [comment]
Following the usual Nuzlocke rules, they begin as soon as you access pokeballs. Is there a way to detect when a player has pokeballs in their inventory?

**Comment by Ordalca** [comment]
Added in dd8c3265, allows starting Nuzlocke by picking up or crafting a poke ball or using a healer, determined by config.  "/nuzlocke begin" also always works (if cheats enabled).  Enabled in v2.1
