### ISSUE TITLE
[Bug] - Starter doesn't have the enforced nickname

### ISSUE THREAD

**Issue by FLalejandro** [Ordalca/Nuzlocke#6]
When the `require-nicknames` setting is set to true, enforcing nicknames works for caught Pokemon, but not for the starter. This is fine since it can be renamed at any moment, but it's just a small nitpick.

**Comment by Ordalca** [comment]
Just to make sure, for this bug, are you doing permission-required:true for it?  If so, it's not getting nicknamed because the nuzlocke hadn't started yet.  I can change that specifically to not require permission, though.

**Comment by FLalejandro** [comment]
Yes, I do have the permission-required:true enabled. That makes a lot of sense 😅 Similar to how it prompts players to rename a Pokémon upon catching, would it be possible to prompt the player to rename the Pokémon in their party upon beginning the Nuzlocke?

**Comment by Ordalca** [comment]
Fixed in a65d46a by removing requirement that nuzlocke begins before nicknaming starts, will be in 2.1.
