### ISSUE TITLE
[Suggestion] - Add Chat Messages confirming /nuzlocke commands

### ISSUE THREAD

**Issue by FLalejandro** [Ordalca/Nuzlocke#7]
This isn't a super big deal, but I noticed when I began running nuzlockes that after executing `/nuzlocke begin`, there wasn't any prompt or notification showing that it began. I thought this meant it was bugged so I ran it a couple of times to make sure it had officially begun. 

It would be nice to see a chat message sent such as "Nuzlocke has now begun!". If you want to be really fancy, you could also use the Minecraft Titles so that a big message pops up in the middle of the screen for dramatic effect.

**Comment by Ordalca** [comment]
Sounds good, I'll look into that for /nuzlocke begin.

**Comment by Ordalca** [comment]
Added 75aeb3c1, adding chat messages for commands running.  Didn't find how to do titles, though.  This will be in v2.1
